name: Notify on pull request creation and comments
on:
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Notify when a new PR is created
      - name: Send Discord Notification for PRs
        if: github.event_name == 'pull_request'
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"New pull request created: ${{ github.event.pull_request.html_url }} by **${{ github.event.pull_request.user.login }}**\"}" \
               ${{ secrets.DISCORD_WEBHOOK_PR }}

      # Notify for PR comments
      - name: Send Discord Notification for PR Comments
        if: github.event_name == 'pull_request_review_comment' && github.event.comment.user.login != 'github-actions[bot]' && github.event.comment.user.login != 'linear[bot]'
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"New comment on pull request: ${{ github.event.pull_request.html_url }} - Comment by **${{ github.event.comment.user.login }}**: ${{ github.event.comment.body }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK_PR }}
