name: Preview Branch Change Check

permissions:
  actions: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - preview
  workflow_dispatch:

jobs:
  check-all-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Find and check all PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'preview',
              state: 'open'
            });
            
            console.log(`Found ${prs.data.length} open PRs`);
            
            for (const pr of prs.data) {
              if (!pr.draft) {
                console.log(`Triggering check for PR #${pr.number}`);
                await github.rest.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: 'pr-check.yml',
                  ref: pr.head.ref,
                  inputs: {
                    pr_number: pr.number.toString()
                  }
                });
              }
            } 
