name: "Validate PRs"

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  validate-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there! 👋 

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

            Valid types:
            - `feat`: A new feature
            - `fix`: A bug fix
            - `docs`: Documentation only changes
            - `style`: Changes that do not affect the meaning of the code
            - `refactor`: A code change that neither fixes a bug nor adds a feature
            - `perf`: A code change that improves performance
            - `test`: Adding missing or correcting existing tests
            - `build`: Changes that affect the build system or external dependencies
            - `ci`: Changes to CI configuration files and scripts
            - `chore`: Other changes that don't modify src or test files
            - `revert`: Reverts a previous commit

            Format: `type: description`

            Error details:
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
